# Ref:
#   nicolas-van/easy-markdown-to-github-pages https://github.com/nicolas-van/easy-markdown-to-github-pages
#   ei1333/library https://github.com/ei1333/library/blob/gh-pages/_config.yml
#   maximevaillancourt/digital-garden-jekyll-template https://github.com/maximevaillancourt/digital-garden-jekyll-template
title: python_2022_lib
include: ["_pages"]
exclude: ["_includes/notes_graph.json"]
lang: ja

# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl: "python_2022_lib"

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink: pretty
relative_permalinks: false

plugins:
  - jemoji
  - jekyll-last-modified-at
  - jekyll-remote-theme
  # - jekyll-relative-links
# theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

# relative_links:
#   enabled: true
#   collections: true

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
